# simple docker-compose.yaml for rockylinux on dockerfile "./dockerfiles/rockylinux8/Dockerfile" and Minio.

version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    container_name: minio
    restart: unless-stopped
    networks:
      - pgfnnet
    volumes:
      - ./volumes/minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_ACCESS_SECRET: minioadmin
    command: server /data --console-address ":9001"
  rockylinux8:
    build: ./dockerfiles/rockylinux8
    container_name: rockylinux
    restart: always
    networks:
      - pgfnnet
    privileged: true
    ports:
      - 5432:5432
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_ACCESS_SECRET: minioadmin

# pgfnnet
networks:
  pgfnnet: